/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BusinessType = IDL.Variant({
  'it' : IDL.Null,
  'repair' : IDL.Null,
  'retail' : IDL.Null,
  'healthcare' : IDL.Null,
  'transportation' : IDL.Null,
  'hospitality' : IDL.Null,
  'finance' : IDL.Null,
  'realEstate' : IDL.Null,
  'cleaning' : IDL.Null,
  'construction' : IDL.Null,
  'other' : IDL.Text,
  'generalTrade' : IDL.Null,
  'entertainment' : IDL.Null,
  'marketing' : IDL.Null,
  'professionalServices' : IDL.Null,
  'education' : IDL.Null,
  'security' : IDL.Null,
  'consulting' : IDL.Null,
  'personalServices' : IDL.Null,
  'skilledTrade' : IDL.Null,
  'legal' : IDL.Null,
  'sales' : IDL.Null,
  'domesticwork' : IDL.Null,
  'petServices' : IDL.Null,
  'socialServices' : IDL.Null,
  'events' : IDL.Null,
  'maintenance' : IDL.Null,
  'wellness' : IDL.Null,
  'catering' : IDL.Null,
  'manufacturing' : IDL.Null,
  'unskilledLabor' : IDL.Null,
  'handyman' : IDL.Null,
  'hairAndBeauty' : IDL.Null,
  'mediar' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentType = IDL.Variant({
  'goodConductCertificate' : IDL.Null,
  'academicQualification' : IDL.Null,
});
export const Document = IDL.Record({
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'docType' : DocumentType,
});
export const ProfilePicture = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
  'rejected' : IDL.Text,
});
export const ProviderProfileView = IDL.Record({
  'principal' : IDL.Principal,
  'engagementEndTime' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'rate' : IDL.Nat,
  'businessType' : BusinessType,
  'ratings' : IDL.Vec(IDL.Nat),
  'description' : IDL.Text,
  'academicDocuments' : IDL.Vec(Document),
  'category' : IDL.Opt(BusinessType),
  'phoneNumber' : IDL.Text,
  'profilePicture' : IDL.Opt(ProfilePicture),
  'location' : Location,
  'goodConductCert' : IDL.Opt(Document),
  'verificationStatus' : VerificationStatus,
  'isEngaged' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'provider' : IDL.Null,
  'backOffice' : IDL.Null,
});
export const ClientProfile = IDL.Record({
  'principal' : IDL.Principal,
  'pinnedLocation' : IDL.Opt(Location),
  'isVerified' : IDL.Bool,
  'phoneNumber' : IDL.Text,
});
export const UserProfileView = IDL.Record({
  'role' : UserRole,
  'clientProfile' : IDL.Opt(ClientProfile),
  'providerProfile' : IDL.Opt(ProviderProfileView),
});
export const Job = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Text,
    'completed' : IDL.Record({ 'rating' : IDL.Nat }),
    'inProgress' : IDL.Null,
  }),
  'client' : IDL.Principal,
  'provider' : IDL.Principal,
  'description' : IDL.Text,
  'payment' : IDL.Nat,
});
export const MPesaConfig = IDL.Record({
  'consumerSecret' : IDL.Text,
  'passkey' : IDL.Text,
  'shortCode' : IDL.Text,
  'consumerKey' : IDL.Text,
  'callbackUrl' : IDL.Text,
});
export const PlatformStats = IDL.Record({
  'totalProviders' : IDL.Nat,
  'totalClients' : IDL.Nat,
});
export const OtpRole = IDL.Variant({
  'client' : IDL.Null,
  'provider' : IDL.Null,
});
export const Time = IDL.Int;
export const ProviderProfileUpdate = IDL.Record({
  'rate' : IDL.Nat,
  'businessType' : BusinessType,
  'description' : IDL.Text,
  'category' : BusinessType,
  'profilePicture' : IDL.Opt(ProfilePicture),
  'location' : Location,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'disengage' : IDL.Func([], [], []),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfileView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClient' : IDL.Func([IDL.Principal], [IDL.Opt(ClientProfile)], ['query']),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
  'getMpesaConfig' : IDL.Func([], [IDL.Opt(MPesaConfig)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getProvider' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProviderProfileView)],
      ['query'],
    ),
  'getProviderResults' : IDL.Func(
      [IDL.Opt(BusinessType)],
      [IDL.Vec(ProviderProfileView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'initiateOtp' : IDL.Func(
      [IDL.Text, OtpRole],
      [IDL.Record({ 'expiresAt' : Time, 'code' : IDL.Text })],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAllProviders' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'role' : UserRole,
          'clientProfile' : IDL.Opt(
            IDL.Record({
              'pinnedLocation' : IDL.Opt(Location),
              'phoneNumber' : IDL.Text,
            })
          ),
          'providerProfile' : IDL.Opt(
            IDL.Record({
              'engagementEndTime' : IDL.Opt(IDL.Int),
              'name' : IDL.Text,
              'businessType' : BusinessType,
              'ratings' : IDL.Vec(IDL.Nat),
              'description' : IDL.Text,
              'academicDocuments' : IDL.Vec(Document),
              'category' : BusinessType,
              'phoneNumber' : IDL.Text,
              'profilePicture' : IDL.Opt(ProfilePicture),
              'location' : Location,
              'goodConductCert' : IDL.Opt(Document),
              'verificationStatus' : VerificationStatus,
              'isEngaged' : IDL.Bool,
            })
          ),
        }),
      ],
      [],
      [],
    ),
  'seedProviders' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Principal, ProviderProfileView))],
      [],
      [],
    ),
  'setEngaged' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'engagementEndTime' : IDL.Opt(IDL.Int) })],
      [],
    ),
  'setMPesaConfig' : IDL.Func([MPesaConfig], [], []),
  'updateClientPinnedLocation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateProviderLocation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateProviderProfile' : IDL.Func([ProviderProfileUpdate], [], []),
  'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BusinessType = IDL.Variant({
    'it' : IDL.Null,
    'repair' : IDL.Null,
    'retail' : IDL.Null,
    'healthcare' : IDL.Null,
    'transportation' : IDL.Null,
    'hospitality' : IDL.Null,
    'finance' : IDL.Null,
    'realEstate' : IDL.Null,
    'cleaning' : IDL.Null,
    'construction' : IDL.Null,
    'other' : IDL.Text,
    'generalTrade' : IDL.Null,
    'entertainment' : IDL.Null,
    'marketing' : IDL.Null,
    'professionalServices' : IDL.Null,
    'education' : IDL.Null,
    'security' : IDL.Null,
    'consulting' : IDL.Null,
    'personalServices' : IDL.Null,
    'skilledTrade' : IDL.Null,
    'legal' : IDL.Null,
    'sales' : IDL.Null,
    'domesticwork' : IDL.Null,
    'petServices' : IDL.Null,
    'socialServices' : IDL.Null,
    'events' : IDL.Null,
    'maintenance' : IDL.Null,
    'wellness' : IDL.Null,
    'catering' : IDL.Null,
    'manufacturing' : IDL.Null,
    'unskilledLabor' : IDL.Null,
    'handyman' : IDL.Null,
    'hairAndBeauty' : IDL.Null,
    'mediar' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentType = IDL.Variant({
    'goodConductCertificate' : IDL.Null,
    'academicQualification' : IDL.Null,
  });
  const Document = IDL.Record({
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'docType' : DocumentType,
  });
  const ProfilePicture = IDL.Record({ 'id' : IDL.Text, 'blob' : ExternalBlob });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const ProviderProfileView = IDL.Record({
    'principal' : IDL.Principal,
    'engagementEndTime' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'rate' : IDL.Nat,
    'businessType' : BusinessType,
    'ratings' : IDL.Vec(IDL.Nat),
    'description' : IDL.Text,
    'academicDocuments' : IDL.Vec(Document),
    'category' : IDL.Opt(BusinessType),
    'phoneNumber' : IDL.Text,
    'profilePicture' : IDL.Opt(ProfilePicture),
    'location' : Location,
    'goodConductCert' : IDL.Opt(Document),
    'verificationStatus' : VerificationStatus,
    'isEngaged' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'client' : IDL.Null,
    'provider' : IDL.Null,
    'backOffice' : IDL.Null,
  });
  const ClientProfile = IDL.Record({
    'principal' : IDL.Principal,
    'pinnedLocation' : IDL.Opt(Location),
    'isVerified' : IDL.Bool,
    'phoneNumber' : IDL.Text,
  });
  const UserProfileView = IDL.Record({
    'role' : UserRole,
    'clientProfile' : IDL.Opt(ClientProfile),
    'providerProfile' : IDL.Opt(ProviderProfileView),
  });
  const Job = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'requested' : IDL.Null,
      'cancelled' : IDL.Text,
      'completed' : IDL.Record({ 'rating' : IDL.Nat }),
      'inProgress' : IDL.Null,
    }),
    'client' : IDL.Principal,
    'provider' : IDL.Principal,
    'description' : IDL.Text,
    'payment' : IDL.Nat,
  });
  const MPesaConfig = IDL.Record({
    'consumerSecret' : IDL.Text,
    'passkey' : IDL.Text,
    'shortCode' : IDL.Text,
    'consumerKey' : IDL.Text,
    'callbackUrl' : IDL.Text,
  });
  const PlatformStats = IDL.Record({
    'totalProviders' : IDL.Nat,
    'totalClients' : IDL.Nat,
  });
  const OtpRole = IDL.Variant({ 'client' : IDL.Null, 'provider' : IDL.Null });
  const Time = IDL.Int;
  const ProviderProfileUpdate = IDL.Record({
    'rate' : IDL.Nat,
    'businessType' : BusinessType,
    'description' : IDL.Text,
    'category' : BusinessType,
    'profilePicture' : IDL.Opt(ProfilePicture),
    'location' : Location,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'disengage' : IDL.Func([], [], []),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfileView)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClient' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ClientProfile)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
    'getMpesaConfig' : IDL.Func([], [IDL.Opt(MPesaConfig)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getProvider' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProviderProfileView)],
        ['query'],
      ),
    'getProviderResults' : IDL.Func(
        [IDL.Opt(BusinessType)],
        [IDL.Vec(ProviderProfileView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'initiateOtp' : IDL.Func(
        [IDL.Text, OtpRole],
        [IDL.Record({ 'expiresAt' : Time, 'code' : IDL.Text })],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAllProviders' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'role' : UserRole,
            'clientProfile' : IDL.Opt(
              IDL.Record({
                'pinnedLocation' : IDL.Opt(Location),
                'phoneNumber' : IDL.Text,
              })
            ),
            'providerProfile' : IDL.Opt(
              IDL.Record({
                'engagementEndTime' : IDL.Opt(IDL.Int),
                'name' : IDL.Text,
                'businessType' : BusinessType,
                'ratings' : IDL.Vec(IDL.Nat),
                'description' : IDL.Text,
                'academicDocuments' : IDL.Vec(Document),
                'category' : BusinessType,
                'phoneNumber' : IDL.Text,
                'profilePicture' : IDL.Opt(ProfilePicture),
                'location' : Location,
                'goodConductCert' : IDL.Opt(Document),
                'verificationStatus' : VerificationStatus,
                'isEngaged' : IDL.Bool,
              })
            ),
          }),
        ],
        [],
        [],
      ),
    'seedProviders' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Principal, ProviderProfileView))],
        [],
        [],
      ),
    'setEngaged' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'engagementEndTime' : IDL.Opt(IDL.Int) })],
        [],
      ),
    'setMPesaConfig' : IDL.Func([MPesaConfig], [], []),
    'updateClientPinnedLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateProviderLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateProviderProfile' : IDL.Func([ProviderProfileUpdate], [], []),
    'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };