/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BusinessType = IDL.Variant({
  'it' : IDL.Null,
  'retail' : IDL.Null,
  'healthcare' : IDL.Null,
  'transportation' : IDL.Null,
  'hospitality' : IDL.Null,
  'finance' : IDL.Null,
  'realEstate' : IDL.Null,
  'cleaning' : IDL.Null,
  'construction' : IDL.Null,
  'other' : IDL.Text,
  'marketing' : IDL.Null,
  'education' : IDL.Null,
  'consulting' : IDL.Null,
  'maintenance' : IDL.Null,
  'wellness' : IDL.Null,
  'catering' : IDL.Null,
  'manufacturing' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'provider' : IDL.Null,
  'backOffice' : IDL.Null,
});
export const ClientProfile = IDL.Record({
  'principal' : IDL.Principal,
  'phoneNumber' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProfilePicture = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
  'rejected' : IDL.Text,
});
export const ProviderProfileView = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'rate' : IDL.Nat,
  'businessType' : BusinessType,
  'ratings' : IDL.Vec(IDL.Nat),
  'description' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'profilePicture' : IDL.Opt(ProfilePicture),
  'location' : Location,
  'verificationStatus' : VerificationStatus,
});
export const UserProfileView = IDL.Record({
  'role' : UserRole,
  'clientProfile' : IDL.Opt(ClientProfile),
  'providerProfile' : IDL.Opt(ProviderProfileView),
});
export const Job = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Text,
    'completed' : IDL.Record({ 'rating' : IDL.Nat }),
    'inProgress' : IDL.Null,
  }),
  'client' : IDL.Principal,
  'provider' : IDL.Principal,
  'description' : IDL.Text,
  'payment' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createOrUpdateClientProfile' : IDL.Func([IDL.Text], [], []),
  'createOrUpdateProviderProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, BusinessType, Location, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClient' : IDL.Func([IDL.Principal], [IDL.Opt(ClientProfile)], ['query']),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
  'getProvider' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProviderProfileView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markJobCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'markJobInProgress' : IDL.Func([IDL.Text], [], []),
  'requestLink' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'role' : UserRole,
          'clientProfile' : IDL.Opt(
            IDL.Record({
              'principal' : IDL.Principal,
              'phoneNumber' : IDL.Text,
            })
          ),
          'providerProfile' : IDL.Opt(
            IDL.Record({
              'principal' : IDL.Principal,
              'name' : IDL.Text,
              'rate' : IDL.Nat,
              'businessType' : BusinessType,
              'ratings' : IDL.Vec(IDL.Nat),
              'description' : IDL.Text,
              'phoneNumber' : IDL.Text,
              'profilePicture' : IDL.Opt(ProfilePicture),
              'location' : Location,
              'verificationStatus' : VerificationStatus,
            })
          ),
        }),
      ],
      [],
      [],
    ),
  'searchProviders' : IDL.Func(
      [IDL.Opt(BusinessType), Location, IDL.Opt(IDL.Nat)],
      [IDL.Vec(ProviderProfileView)],
      ['query'],
    ),
  'setUserRole' : IDL.Func([UserRole], [], []),
  'updateVerificationStatus' : IDL.Func(
      [IDL.Principal, VerificationStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BusinessType = IDL.Variant({
    'it' : IDL.Null,
    'retail' : IDL.Null,
    'healthcare' : IDL.Null,
    'transportation' : IDL.Null,
    'hospitality' : IDL.Null,
    'finance' : IDL.Null,
    'realEstate' : IDL.Null,
    'cleaning' : IDL.Null,
    'construction' : IDL.Null,
    'other' : IDL.Text,
    'marketing' : IDL.Null,
    'education' : IDL.Null,
    'consulting' : IDL.Null,
    'maintenance' : IDL.Null,
    'wellness' : IDL.Null,
    'catering' : IDL.Null,
    'manufacturing' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'client' : IDL.Null,
    'provider' : IDL.Null,
    'backOffice' : IDL.Null,
  });
  const ClientProfile = IDL.Record({
    'principal' : IDL.Principal,
    'phoneNumber' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProfilePicture = IDL.Record({ 'id' : IDL.Text, 'blob' : ExternalBlob });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const ProviderProfileView = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'rate' : IDL.Nat,
    'businessType' : BusinessType,
    'ratings' : IDL.Vec(IDL.Nat),
    'description' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'profilePicture' : IDL.Opt(ProfilePicture),
    'location' : Location,
    'verificationStatus' : VerificationStatus,
  });
  const UserProfileView = IDL.Record({
    'role' : UserRole,
    'clientProfile' : IDL.Opt(ClientProfile),
    'providerProfile' : IDL.Opt(ProviderProfileView),
  });
  const Job = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'requested' : IDL.Null,
      'cancelled' : IDL.Text,
      'completed' : IDL.Record({ 'rating' : IDL.Nat }),
      'inProgress' : IDL.Null,
    }),
    'client' : IDL.Principal,
    'provider' : IDL.Principal,
    'description' : IDL.Text,
    'payment' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createOrUpdateClientProfile' : IDL.Func([IDL.Text], [], []),
    'createOrUpdateProviderProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, BusinessType, Location, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClient' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ClientProfile)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
    'getProvider' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProviderProfileView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markJobCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'markJobInProgress' : IDL.Func([IDL.Text], [], []),
    'requestLink' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'role' : UserRole,
            'clientProfile' : IDL.Opt(
              IDL.Record({
                'principal' : IDL.Principal,
                'phoneNumber' : IDL.Text,
              })
            ),
            'providerProfile' : IDL.Opt(
              IDL.Record({
                'principal' : IDL.Principal,
                'name' : IDL.Text,
                'rate' : IDL.Nat,
                'businessType' : BusinessType,
                'ratings' : IDL.Vec(IDL.Nat),
                'description' : IDL.Text,
                'phoneNumber' : IDL.Text,
                'profilePicture' : IDL.Opt(ProfilePicture),
                'location' : Location,
                'verificationStatus' : VerificationStatus,
              })
            ),
          }),
        ],
        [],
        [],
      ),
    'searchProviders' : IDL.Func(
        [IDL.Opt(BusinessType), Location, IDL.Opt(IDL.Nat)],
        [IDL.Vec(ProviderProfileView)],
        ['query'],
      ),
    'setUserRole' : IDL.Func([UserRole], [], []),
    'updateVerificationStatus' : IDL.Func(
        [IDL.Principal, VerificationStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };