/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BusinessType = { 'it' : null } |
  { 'repair' : null } |
  { 'retail' : null } |
  { 'healthcare' : null } |
  { 'transportation' : null } |
  { 'hospitality' : null } |
  { 'finance' : null } |
  { 'realEstate' : null } |
  { 'cleaning' : null } |
  { 'construction' : null } |
  { 'other' : string } |
  { 'generalTrade' : null } |
  { 'entertainment' : null } |
  { 'marketing' : null } |
  { 'professionalServices' : null } |
  { 'education' : null } |
  { 'security' : null } |
  { 'consulting' : null } |
  { 'personalServices' : null } |
  { 'skilledTrade' : null } |
  { 'legal' : null } |
  { 'sales' : null } |
  { 'domesticwork' : null } |
  { 'petServices' : null } |
  { 'socialServices' : null } |
  { 'events' : null } |
  { 'maintenance' : null } |
  { 'wellness' : null } |
  { 'catering' : null } |
  { 'manufacturing' : null } |
  { 'unskilledLabor' : null } |
  { 'handyman' : null } |
  { 'hairAndBeauty' : null } |
  { 'mediar' : null };
export interface ClientProfile {
  'principal' : Principal,
  'phoneNumber' : string,
}
export interface Document {
  'blob' : ExternalBlob,
  'filename' : string,
  'docType' : DocumentType,
}
export type DocumentType = { 'goodConductCertificate' : null } |
  { 'academicQualification' : null };
export type ExternalBlob = Uint8Array;
export interface Job {
  'id' : string,
  'status' : { 'requested' : null } |
    { 'cancelled' : string } |
    { 'completed' : { 'rating' : bigint } } |
    { 'inProgress' : null },
  'client' : Principal,
  'provider' : Principal,
  'description' : string,
  'payment' : bigint,
}
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'address' : string,
}
export interface MPesaConfig {
  'consumerSecret' : string,
  'passkey' : string,
  'shortCode' : string,
  'consumerKey' : string,
  'callbackUrl' : string,
}
export interface PlatformStats {
  'totalProviders' : bigint,
  'totalClients' : bigint,
}
export interface ProfilePicture { 'id' : string, 'blob' : ExternalBlob }
export interface ProviderPreview {
  'provider' : ProviderProfileView,
  'isEngaged' : boolean,
}
export interface ProviderProfileView {
  'principal' : Principal,
  'name' : string,
  'rate' : bigint,
  'businessType' : BusinessType,
  'ratings' : Array<bigint>,
  'description' : string,
  'academicDocuments' : Array<Document>,
  'phoneNumber' : string,
  'profilePicture' : [] | [ProfilePicture],
  'location' : Location,
  'goodConductCert' : [] | [Document],
  'verificationStatus' : VerificationStatus,
  'isEngaged' : boolean,
}
export interface UserProfileView {
  'role' : UserRole,
  'clientProfile' : [] | [ClientProfile],
  'providerProfile' : [] | [ProviderProfileView],
}
export type UserRole = { 'client' : null } |
  { 'provider' : null } |
  { 'backOffice' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'unverified' : null } |
  { 'rejected' : string };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDocumentToProvider' : ActorMethod<[string], undefined>,
  'addProfilePictureToProvider' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelJob' : ActorMethod<[string, string], undefined>,
  'createOrUpdateClientProfile' : ActorMethod<[string], undefined>,
  'createOrUpdateProviderProfile' : ActorMethod<
    [string, bigint, BusinessType, Location, string, string, boolean],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClient' : ActorMethod<[Principal], [] | [ClientProfile]>,
  'getJob' : ActorMethod<[string], [] | [Job]>,
  'getMpesaConfig' : ActorMethod<[], [] | [MPesaConfig]>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getProvider' : ActorMethod<[Principal], [] | [ProviderProfileView]>,
  'getProviderPreview' : ActorMethod<[Principal], [] | [ProviderPreview]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markJobCompleted' : ActorMethod<[string, bigint], undefined>,
  'markJobInProgress' : ActorMethod<[string], undefined>,
  'providerHasEngagedJob' : ActorMethod<[Principal], boolean>,
  'requestLink' : ActorMethod<[Principal, bigint, string], string>,
  'saveCallerUserProfile' : ActorMethod<
    [
      {
        'role' : UserRole,
        'clientProfile' : [] | [
          { 'principal' : Principal, 'phoneNumber' : string }
        ],
        'providerProfile' : [] | [
          {
            'principal' : Principal,
            'name' : string,
            'rate' : bigint,
            'businessType' : BusinessType,
            'ratings' : Array<bigint>,
            'description' : string,
            'academicDocuments' : Array<Document>,
            'phoneNumber' : string,
            'profilePicture' : [] | [ProfilePicture],
            'location' : Location,
            'goodConductCert' : [] | [Document],
            'verificationStatus' : VerificationStatus,
            'isEngaged' : boolean,
          }
        ],
      },
    ],
    undefined
  >,
  'searchProviders' : ActorMethod<
    [[] | [BusinessType], Location, [] | [bigint]],
    Array<ProviderProfileView>
  >,
  'setMPesaConfig' : ActorMethod<[MPesaConfig], undefined>,
  'setUserRole' : ActorMethod<[UserRole], undefined>,
  'updateEngagementStatus' : ActorMethod<[boolean], undefined>,
  'updateVerificationStatus' : ActorMethod<
    [Principal, VerificationStatus],
    undefined
  >,
  'uploadDocument' : ActorMethod<[DocumentType, string, ExternalBlob], string>,
  'uploadProfilePicture' : ActorMethod<[string, ExternalBlob], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];