/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProviderProfileView {
    principal: Principal;
    engagementEndTime?: bigint;
    name: string;
    rate: bigint;
    businessType: BusinessType;
    ratings: Array<bigint>;
    description: string;
    academicDocuments: Array<Document>;
    phoneNumber: string;
    profilePicture?: ProfilePicture;
    location: Location;
    goodConductCert?: Document;
    verificationStatus: VerificationStatus;
    isEngaged: boolean;
}
export interface Location {
    latitude: number;
    longitude: number;
    address: string;
}
export type Time = bigint;
export type BusinessType = {
    __kind__: "it";
    it: null;
} | {
    __kind__: "repair";
    repair: null;
} | {
    __kind__: "retail";
    retail: null;
} | {
    __kind__: "healthcare";
    healthcare: null;
} | {
    __kind__: "transportation";
    transportation: null;
} | {
    __kind__: "hospitality";
    hospitality: null;
} | {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "realEstate";
    realEstate: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "construction";
    construction: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "generalTrade";
    generalTrade: null;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "marketing";
    marketing: null;
} | {
    __kind__: "professionalServices";
    professionalServices: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "security";
    security: null;
} | {
    __kind__: "consulting";
    consulting: null;
} | {
    __kind__: "personalServices";
    personalServices: null;
} | {
    __kind__: "skilledTrade";
    skilledTrade: null;
} | {
    __kind__: "legal";
    legal: null;
} | {
    __kind__: "sales";
    sales: null;
} | {
    __kind__: "domesticwork";
    domesticwork: null;
} | {
    __kind__: "petServices";
    petServices: null;
} | {
    __kind__: "socialServices";
    socialServices: null;
} | {
    __kind__: "events";
    events: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
} | {
    __kind__: "wellness";
    wellness: null;
} | {
    __kind__: "catering";
    catering: null;
} | {
    __kind__: "manufacturing";
    manufacturing: null;
} | {
    __kind__: "unskilledLabor";
    unskilledLabor: null;
} | {
    __kind__: "handyman";
    handyman: null;
} | {
    __kind__: "hairAndBeauty";
    hairAndBeauty: null;
} | {
    __kind__: "mediar";
    mediar: null;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    blob: ExternalBlob;
    filename: string;
    docType: DocumentType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ProviderProfileUpdate {
    rate: bigint;
    businessType: BusinessType;
    description: string;
    profilePicture?: ProfilePicture;
    location: Location;
}
export interface ProfilePicture {
    id: string;
    blob: ExternalBlob;
}
export type VerificationStatus = {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
};
export interface Job {
    id: string;
    status: {
        __kind__: "requested";
        requested: null;
    } | {
        __kind__: "cancelled";
        cancelled: string;
    } | {
        __kind__: "completed";
        completed: {
            rating: bigint;
        };
    } | {
        __kind__: "inProgress";
        inProgress: null;
    };
    client: Principal;
    provider: Principal;
    description: string;
    payment: bigint;
}
export interface UserProfileView {
    role: UserRole;
    clientProfile?: ClientProfile;
    providerProfile?: ProviderProfileView;
}
export interface ClientProfile {
    principal: Principal;
    pinnedLocation?: Location;
    isVerified: boolean;
    phoneNumber: string;
}
export interface PlatformStats {
    totalProviders: bigint;
    totalClients: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface MPesaConfig {
    consumerSecret: string;
    passkey: string;
    shortCode: string;
    consumerKey: string;
    callbackUrl: string;
}
export enum DocumentType {
    goodConductCertificate = "goodConductCertificate",
    academicQualification = "academicQualification"
}
export enum OtpRole {
    client = "client",
    provider = "provider"
}
export enum UserRole {
    client = "client",
    provider = "provider",
    backOffice = "backOffice"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    disengage(): Promise<void>;
    getAllProviders(): Promise<Array<ProviderProfileView>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClient(client: Principal): Promise<ClientProfile | null>;
    getJob(jobId: string): Promise<Job | null>;
    getMpesaConfig(): Promise<MPesaConfig | null>;
    getPlatformStats(): Promise<PlatformStats>;
    getProvider(provider: Principal): Promise<ProviderProfileView | null>;
    getProviderResults(category: BusinessType | null): Promise<Array<ProviderProfileView>>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    initiateOtp(phoneNumber: string, role: OtpRole): Promise<{
        expiresAt: Time;
        code: string;
    }>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: {
        role: UserRole;
        clientProfile?: {
            pinnedLocation?: Location;
            phoneNumber: string;
        };
        providerProfile?: {
            engagementEndTime?: bigint;
            name: string;
            businessType: BusinessType;
            ratings: Array<bigint>;
            description: string;
            academicDocuments: Array<Document>;
            phoneNumber: string;
            profilePicture?: ProfilePicture;
            location: Location;
            goodConductCert?: Document;
            verificationStatus: VerificationStatus;
            isEngaged: boolean;
        };
    }): Promise<void>;
    setEngaged(hours: bigint): Promise<{
        engagementEndTime?: bigint;
    }>;
    setMPesaConfig(config: MPesaConfig): Promise<void>;
    updateClientPinnedLocation(latitude: number, longitude: number, address: string): Promise<void>;
    updateProviderLocation(latitude: number, longitude: number, address: string): Promise<void>;
    updateProviderProfile(update: ProviderProfileUpdate): Promise<void>;
    verifyOtp(code: string): Promise<boolean>;
}
import type { BusinessType as _BusinessType, ClientProfile as _ClientProfile, Document as _Document, DocumentType as _DocumentType, ExternalBlob as _ExternalBlob, Job as _Job, Location as _Location, MPesaConfig as _MPesaConfig, OtpRole as _OtpRole, ProfilePicture as _ProfilePicture, ProviderProfileUpdate as _ProviderProfileUpdate, ProviderProfileView as _ProviderProfileView, UserProfileView as _UserProfileView, UserRole as _UserRole, UserRole__1 as _UserRole__1, VerificationStatus as _VerificationStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async disengage(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disengage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disengage();
            return result;
        }
    }
    async getAllProviders(): Promise<Array<ProviderProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProviders();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProviders();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: Principal): Promise<ClientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMpesaConfig(): Promise<MPesaConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMpesaConfig();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMpesaConfig();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getProvider(arg0: Principal): Promise<ProviderProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderResults(arg0: BusinessType | null): Promise<Array<ProviderProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderResults(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderResults(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateOtp(arg0: string, arg1: OtpRole): Promise<{
        expiresAt: Time;
        code: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateOtp(arg0, to_candid_OtpRole_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateOtp(arg0, to_candid_OtpRole_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: {
        role: UserRole;
        clientProfile?: {
            pinnedLocation?: Location;
            phoneNumber: string;
        };
        providerProfile?: {
            engagementEndTime?: bigint;
            name: string;
            businessType: BusinessType;
            ratings: Array<bigint>;
            description: string;
            academicDocuments: Array<Document>;
            phoneNumber: string;
            profilePicture?: ProfilePicture;
            location: Location;
            goodConductCert?: Document;
            verificationStatus: VerificationStatus;
            isEngaged: boolean;
        };
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_record_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_record_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setEngaged(arg0: bigint): Promise<{
        engagementEndTime?: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setEngaged(arg0);
                return from_candid_record_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEngaged(arg0);
            return from_candid_record_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMPesaConfig(arg0: MPesaConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMPesaConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMPesaConfig(arg0);
            return result;
        }
    }
    async updateClientPinnedLocation(arg0: number, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientPinnedLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientPinnedLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProviderLocation(arg0: number, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProviderLocation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProviderLocation(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProviderProfile(arg0: ProviderProfileUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProviderProfile(await to_candid_ProviderProfileUpdate_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProviderProfile(await to_candid_ProviderProfileUpdate_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyOtp(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0);
            return result;
        }
    }
}
function from_candid_BusinessType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessType): BusinessType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ClientProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientProfile): ClientProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Job_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_ProfilePicture_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfilePicture): Promise<ProfilePicture> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ProviderProfileView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderProfileView): Promise<ProviderProfileView> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfileView_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): Promise<UserProfileView> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfilePicture]): Promise<ProfilePicture | null> {
    return value.length === 0 ? null : await from_candid_ProfilePicture_n23(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Promise<Document | null> {
    return value.length === 0 ? null : await from_candid_Document_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): Promise<UserProfileView | null> {
    return value.length === 0 ? null : await from_candid_UserProfileView_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientProfile]): ClientProfile | null {
    return value.length === 0 ? null : from_candid_ClientProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProviderProfileView]): Promise<ProviderProfileView | null> {
    return value.length === 0 ? null : await from_candid_ProviderProfileView_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MPesaConfig]): MPesaConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    engagementEndTime: [] | [bigint];
    name: string;
    rate: bigint;
    businessType: _BusinessType;
    ratings: Array<bigint>;
    description: string;
    academicDocuments: Array<_Document>;
    phoneNumber: string;
    profilePicture: [] | [_ProfilePicture];
    location: _Location;
    goodConductCert: [] | [_Document];
    verificationStatus: _VerificationStatus;
    isEngaged: boolean;
}): Promise<{
    principal: Principal;
    engagementEndTime?: bigint;
    name: string;
    rate: bigint;
    businessType: BusinessType;
    ratings: Array<bigint>;
    description: string;
    academicDocuments: Array<Document>;
    phoneNumber: string;
    profilePicture?: ProfilePicture;
    location: Location;
    goodConductCert?: Document;
    verificationStatus: VerificationStatus;
    isEngaged: boolean;
}> {
    return {
        principal: value.principal,
        engagementEndTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.engagementEndTime)),
        name: value.name,
        rate: value.rate,
        businessType: from_candid_BusinessType_n14(_uploadFile, _downloadFile, value.businessType),
        ratings: value.ratings,
        description: value.description,
        academicDocuments: await from_candid_vec_n16(_uploadFile, _downloadFile, value.academicDocuments),
        phoneNumber: value.phoneNumber,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.profilePicture)),
        location: value.location,
        goodConductCert: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.goodConductCert)),
        verificationStatus: from_candid_VerificationStatus_n26(_uploadFile, _downloadFile, value.verificationStatus),
        isEngaged: value.isEngaged
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    filename: string;
    docType: _DocumentType;
}): Promise<{
    blob: ExternalBlob;
    filename: string;
    docType: DocumentType;
}> {
    return {
        blob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.blob),
        filename: value.filename,
        docType: from_candid_DocumentType_n20(_uploadFile, _downloadFile, value.docType)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
}): Promise<{
    id: string;
    blob: ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.blob)
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _UserRole;
    clientProfile: [] | [_ClientProfile];
    providerProfile: [] | [_ProviderProfileView];
}): Promise<{
    role: UserRole;
    clientProfile?: ClientProfile;
    providerProfile?: ProviderProfileView;
}> {
    return {
        role: from_candid_UserRole_n31(_uploadFile, _downloadFile, value.role),
        clientProfile: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.clientProfile)),
        providerProfile: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.providerProfile))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    pinnedLocation: [] | [_Location];
    isVerified: boolean;
    phoneNumber: string;
}): {
    principal: Principal;
    pinnedLocation?: Location;
    isVerified: boolean;
    phoneNumber: string;
} {
    return {
        principal: value.principal,
        pinnedLocation: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.pinnedLocation)),
        isVerified: value.isVerified,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        requested: null;
    } | {
        cancelled: string;
    } | {
        completed: {
            rating: bigint;
        };
    } | {
        inProgress: null;
    };
    client: Principal;
    provider: Principal;
    description: string;
    payment: bigint;
}): {
    id: string;
    status: {
        __kind__: "requested";
        requested: null;
    } | {
        __kind__: "cancelled";
        cancelled: string;
    } | {
        __kind__: "completed";
        completed: {
            rating: bigint;
        };
    } | {
        __kind__: "inProgress";
        inProgress: null;
    };
    client: Principal;
    provider: Principal;
    description: string;
    payment: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n43(_uploadFile, _downloadFile, value.status),
        client: value.client,
        provider: value.provider,
        description: value.description,
        payment: value.payment
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    engagementEndTime: [] | [bigint];
}): {
    engagementEndTime?: bigint;
} {
    return {
        engagementEndTime: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.engagementEndTime))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    it: null;
} | {
    repair: null;
} | {
    retail: null;
} | {
    healthcare: null;
} | {
    transportation: null;
} | {
    hospitality: null;
} | {
    finance: null;
} | {
    realEstate: null;
} | {
    cleaning: null;
} | {
    construction: null;
} | {
    other: string;
} | {
    generalTrade: null;
} | {
    entertainment: null;
} | {
    marketing: null;
} | {
    professionalServices: null;
} | {
    education: null;
} | {
    security: null;
} | {
    consulting: null;
} | {
    personalServices: null;
} | {
    skilledTrade: null;
} | {
    legal: null;
} | {
    sales: null;
} | {
    domesticwork: null;
} | {
    petServices: null;
} | {
    socialServices: null;
} | {
    events: null;
} | {
    maintenance: null;
} | {
    wellness: null;
} | {
    catering: null;
} | {
    manufacturing: null;
} | {
    unskilledLabor: null;
} | {
    handyman: null;
} | {
    hairAndBeauty: null;
} | {
    mediar: null;
}): {
    __kind__: "it";
    it: null;
} | {
    __kind__: "repair";
    repair: null;
} | {
    __kind__: "retail";
    retail: null;
} | {
    __kind__: "healthcare";
    healthcare: null;
} | {
    __kind__: "transportation";
    transportation: null;
} | {
    __kind__: "hospitality";
    hospitality: null;
} | {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "realEstate";
    realEstate: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "construction";
    construction: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "generalTrade";
    generalTrade: null;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "marketing";
    marketing: null;
} | {
    __kind__: "professionalServices";
    professionalServices: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "security";
    security: null;
} | {
    __kind__: "consulting";
    consulting: null;
} | {
    __kind__: "personalServices";
    personalServices: null;
} | {
    __kind__: "skilledTrade";
    skilledTrade: null;
} | {
    __kind__: "legal";
    legal: null;
} | {
    __kind__: "sales";
    sales: null;
} | {
    __kind__: "domesticwork";
    domesticwork: null;
} | {
    __kind__: "petServices";
    petServices: null;
} | {
    __kind__: "socialServices";
    socialServices: null;
} | {
    __kind__: "events";
    events: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
} | {
    __kind__: "wellness";
    wellness: null;
} | {
    __kind__: "catering";
    catering: null;
} | {
    __kind__: "manufacturing";
    manufacturing: null;
} | {
    __kind__: "unskilledLabor";
    unskilledLabor: null;
} | {
    __kind__: "handyman";
    handyman: null;
} | {
    __kind__: "hairAndBeauty";
    hairAndBeauty: null;
} | {
    __kind__: "mediar";
    mediar: null;
} {
    return "it" in value ? {
        __kind__: "it",
        it: value.it
    } : "repair" in value ? {
        __kind__: "repair",
        repair: value.repair
    } : "retail" in value ? {
        __kind__: "retail",
        retail: value.retail
    } : "healthcare" in value ? {
        __kind__: "healthcare",
        healthcare: value.healthcare
    } : "transportation" in value ? {
        __kind__: "transportation",
        transportation: value.transportation
    } : "hospitality" in value ? {
        __kind__: "hospitality",
        hospitality: value.hospitality
    } : "finance" in value ? {
        __kind__: "finance",
        finance: value.finance
    } : "realEstate" in value ? {
        __kind__: "realEstate",
        realEstate: value.realEstate
    } : "cleaning" in value ? {
        __kind__: "cleaning",
        cleaning: value.cleaning
    } : "construction" in value ? {
        __kind__: "construction",
        construction: value.construction
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "generalTrade" in value ? {
        __kind__: "generalTrade",
        generalTrade: value.generalTrade
    } : "entertainment" in value ? {
        __kind__: "entertainment",
        entertainment: value.entertainment
    } : "marketing" in value ? {
        __kind__: "marketing",
        marketing: value.marketing
    } : "professionalServices" in value ? {
        __kind__: "professionalServices",
        professionalServices: value.professionalServices
    } : "education" in value ? {
        __kind__: "education",
        education: value.education
    } : "security" in value ? {
        __kind__: "security",
        security: value.security
    } : "consulting" in value ? {
        __kind__: "consulting",
        consulting: value.consulting
    } : "personalServices" in value ? {
        __kind__: "personalServices",
        personalServices: value.personalServices
    } : "skilledTrade" in value ? {
        __kind__: "skilledTrade",
        skilledTrade: value.skilledTrade
    } : "legal" in value ? {
        __kind__: "legal",
        legal: value.legal
    } : "sales" in value ? {
        __kind__: "sales",
        sales: value.sales
    } : "domesticwork" in value ? {
        __kind__: "domesticwork",
        domesticwork: value.domesticwork
    } : "petServices" in value ? {
        __kind__: "petServices",
        petServices: value.petServices
    } : "socialServices" in value ? {
        __kind__: "socialServices",
        socialServices: value.socialServices
    } : "events" in value ? {
        __kind__: "events",
        events: value.events
    } : "maintenance" in value ? {
        __kind__: "maintenance",
        maintenance: value.maintenance
    } : "wellness" in value ? {
        __kind__: "wellness",
        wellness: value.wellness
    } : "catering" in value ? {
        __kind__: "catering",
        catering: value.catering
    } : "manufacturing" in value ? {
        __kind__: "manufacturing",
        manufacturing: value.manufacturing
    } : "unskilledLabor" in value ? {
        __kind__: "unskilledLabor",
        unskilledLabor: value.unskilledLabor
    } : "handyman" in value ? {
        __kind__: "handyman",
        handyman: value.handyman
    } : "hairAndBeauty" in value ? {
        __kind__: "hairAndBeauty",
        hairAndBeauty: value.hairAndBeauty
    } : "mediar" in value ? {
        __kind__: "mediar",
        mediar: value.mediar
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goodConductCertificate: null;
} | {
    academicQualification: null;
}): DocumentType {
    return "goodConductCertificate" in value ? DocumentType.goodConductCertificate : "academicQualification" in value ? DocumentType.academicQualification : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: string;
}): {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
} {
    return "verified" in value ? {
        __kind__: "verified",
        verified: value.verified
    } : "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "unverified" in value ? {
        __kind__: "unverified",
        unverified: value.unverified
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    provider: null;
} | {
    backOffice: null;
}): UserRole {
    return "client" in value ? UserRole.client : "provider" in value ? UserRole.provider : "backOffice" in value ? UserRole.backOffice : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    cancelled: string;
} | {
    completed: {
        rating: bigint;
    };
} | {
    inProgress: null;
}): {
    __kind__: "requested";
    requested: null;
} | {
    __kind__: "cancelled";
    cancelled: string;
} | {
    __kind__: "completed";
    completed: {
        rating: bigint;
    };
} | {
    __kind__: "inProgress";
    inProgress: null;
} {
    return "requested" in value ? {
        __kind__: "requested",
        requested: value.requested
    } : "cancelled" in value ? {
        __kind__: "cancelled",
        cancelled: value.cancelled
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: value.inProgress
    } : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderProfileView>): Promise<Array<ProviderProfileView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ProviderProfileView_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n17(_uploadFile, _downloadFile, x)));
}
function to_candid_BusinessType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): _BusinessType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentType_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
async function to_candid_Document_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Document): Promise<_Document> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OtpRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OtpRole): _OtpRole {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function to_candid_ProfilePicture_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfilePicture): Promise<_ProfilePicture> {
    return await to_candid_record_n62(_uploadFile, _downloadFile, value);
}
async function to_candid_ProviderProfileUpdate_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProviderProfileUpdate): Promise<_ProviderProfileUpdate> {
    return await to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType | null): [] | [_BusinessType] {
    return value === null ? candid_none() : candid_some(to_candid_BusinessType_n46(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: UserRole;
    clientProfile?: {
        pinnedLocation?: Location;
        phoneNumber: string;
    };
    providerProfile?: {
        engagementEndTime?: bigint;
        name: string;
        businessType: BusinessType;
        ratings: Array<bigint>;
        description: string;
        academicDocuments: Array<Document>;
        phoneNumber: string;
        profilePicture?: ProfilePicture;
        location: Location;
        goodConductCert?: Document;
        verificationStatus: VerificationStatus;
        isEngaged: boolean;
    };
}): Promise<{
    role: _UserRole;
    clientProfile: [] | [{
            pinnedLocation: [] | [_Location];
            phoneNumber: string;
        }];
    providerProfile: [] | [{
            engagementEndTime: [] | [bigint];
            name: string;
            businessType: _BusinessType;
            ratings: Array<bigint>;
            description: string;
            academicDocuments: Array<_Document>;
            phoneNumber: string;
            profilePicture: [] | [_ProfilePicture];
            location: _Location;
            goodConductCert: [] | [_Document];
            verificationStatus: _VerificationStatus;
            isEngaged: boolean;
        }];
}> {
    return {
        role: to_candid_UserRole_n51(_uploadFile, _downloadFile, value.role),
        clientProfile: value.clientProfile ? candid_some(to_candid_record_n53(_uploadFile, _downloadFile, value.clientProfile)) : candid_none(),
        providerProfile: value.providerProfile ? candid_some(await to_candid_record_n54(_uploadFile, _downloadFile, value.providerProfile)) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pinnedLocation?: Location;
    phoneNumber: string;
}): {
    pinnedLocation: [] | [_Location];
    phoneNumber: string;
} {
    return {
        pinnedLocation: value.pinnedLocation ? candid_some(value.pinnedLocation) : candid_none(),
        phoneNumber: value.phoneNumber
    };
}
async function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    engagementEndTime?: bigint;
    name: string;
    businessType: BusinessType;
    ratings: Array<bigint>;
    description: string;
    academicDocuments: Array<Document>;
    phoneNumber: string;
    profilePicture?: ProfilePicture;
    location: Location;
    goodConductCert?: Document;
    verificationStatus: VerificationStatus;
    isEngaged: boolean;
}): Promise<{
    engagementEndTime: [] | [bigint];
    name: string;
    businessType: _BusinessType;
    ratings: Array<bigint>;
    description: string;
    academicDocuments: Array<_Document>;
    phoneNumber: string;
    profilePicture: [] | [_ProfilePicture];
    location: _Location;
    goodConductCert: [] | [_Document];
    verificationStatus: _VerificationStatus;
    isEngaged: boolean;
}> {
    return {
        engagementEndTime: value.engagementEndTime ? candid_some(value.engagementEndTime) : candid_none(),
        name: value.name,
        businessType: to_candid_BusinessType_n46(_uploadFile, _downloadFile, value.businessType),
        ratings: value.ratings,
        description: value.description,
        academicDocuments: await to_candid_vec_n55(_uploadFile, _downloadFile, value.academicDocuments),
        phoneNumber: value.phoneNumber,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ProfilePicture_n61(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        location: value.location,
        goodConductCert: value.goodConductCert ? candid_some(await to_candid_Document_n56(_uploadFile, _downloadFile, value.goodConductCert)) : candid_none(),
        verificationStatus: to_candid_VerificationStatus_n63(_uploadFile, _downloadFile, value.verificationStatus),
        isEngaged: value.isEngaged
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    filename: string;
    docType: DocumentType;
}): Promise<{
    blob: _ExternalBlob;
    filename: string;
    docType: _DocumentType;
}> {
    return {
        blob: await to_candid_ExternalBlob_n58(_uploadFile, _downloadFile, value.blob),
        filename: value.filename,
        docType: to_candid_DocumentType_n59(_uploadFile, _downloadFile, value.docType)
    };
}
async function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: ExternalBlob;
}): Promise<{
    id: string;
    blob: _ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n58(_uploadFile, _downloadFile, value.blob)
    };
}
async function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rate: bigint;
    businessType: BusinessType;
    description: string;
    profilePicture?: ProfilePicture;
    location: Location;
}): Promise<{
    rate: bigint;
    businessType: _BusinessType;
    description: string;
    profilePicture: [] | [_ProfilePicture];
    location: _Location;
}> {
    return {
        rate: value.rate,
        businessType: to_candid_BusinessType_n46(_uploadFile, _downloadFile, value.businessType),
        description: value.description,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ProfilePicture_n61(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        location: value.location
    };
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "it";
    it: null;
} | {
    __kind__: "repair";
    repair: null;
} | {
    __kind__: "retail";
    retail: null;
} | {
    __kind__: "healthcare";
    healthcare: null;
} | {
    __kind__: "transportation";
    transportation: null;
} | {
    __kind__: "hospitality";
    hospitality: null;
} | {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "realEstate";
    realEstate: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "construction";
    construction: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "generalTrade";
    generalTrade: null;
} | {
    __kind__: "entertainment";
    entertainment: null;
} | {
    __kind__: "marketing";
    marketing: null;
} | {
    __kind__: "professionalServices";
    professionalServices: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "security";
    security: null;
} | {
    __kind__: "consulting";
    consulting: null;
} | {
    __kind__: "personalServices";
    personalServices: null;
} | {
    __kind__: "skilledTrade";
    skilledTrade: null;
} | {
    __kind__: "legal";
    legal: null;
} | {
    __kind__: "sales";
    sales: null;
} | {
    __kind__: "domesticwork";
    domesticwork: null;
} | {
    __kind__: "petServices";
    petServices: null;
} | {
    __kind__: "socialServices";
    socialServices: null;
} | {
    __kind__: "events";
    events: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
} | {
    __kind__: "wellness";
    wellness: null;
} | {
    __kind__: "catering";
    catering: null;
} | {
    __kind__: "manufacturing";
    manufacturing: null;
} | {
    __kind__: "unskilledLabor";
    unskilledLabor: null;
} | {
    __kind__: "handyman";
    handyman: null;
} | {
    __kind__: "hairAndBeauty";
    hairAndBeauty: null;
} | {
    __kind__: "mediar";
    mediar: null;
}): {
    it: null;
} | {
    repair: null;
} | {
    retail: null;
} | {
    healthcare: null;
} | {
    transportation: null;
} | {
    hospitality: null;
} | {
    finance: null;
} | {
    realEstate: null;
} | {
    cleaning: null;
} | {
    construction: null;
} | {
    other: string;
} | {
    generalTrade: null;
} | {
    entertainment: null;
} | {
    marketing: null;
} | {
    professionalServices: null;
} | {
    education: null;
} | {
    security: null;
} | {
    consulting: null;
} | {
    personalServices: null;
} | {
    skilledTrade: null;
} | {
    legal: null;
} | {
    sales: null;
} | {
    domesticwork: null;
} | {
    petServices: null;
} | {
    socialServices: null;
} | {
    events: null;
} | {
    maintenance: null;
} | {
    wellness: null;
} | {
    catering: null;
} | {
    manufacturing: null;
} | {
    unskilledLabor: null;
} | {
    handyman: null;
} | {
    hairAndBeauty: null;
} | {
    mediar: null;
} {
    return value.__kind__ === "it" ? {
        it: value.it
    } : value.__kind__ === "repair" ? {
        repair: value.repair
    } : value.__kind__ === "retail" ? {
        retail: value.retail
    } : value.__kind__ === "healthcare" ? {
        healthcare: value.healthcare
    } : value.__kind__ === "transportation" ? {
        transportation: value.transportation
    } : value.__kind__ === "hospitality" ? {
        hospitality: value.hospitality
    } : value.__kind__ === "finance" ? {
        finance: value.finance
    } : value.__kind__ === "realEstate" ? {
        realEstate: value.realEstate
    } : value.__kind__ === "cleaning" ? {
        cleaning: value.cleaning
    } : value.__kind__ === "construction" ? {
        construction: value.construction
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "generalTrade" ? {
        generalTrade: value.generalTrade
    } : value.__kind__ === "entertainment" ? {
        entertainment: value.entertainment
    } : value.__kind__ === "marketing" ? {
        marketing: value.marketing
    } : value.__kind__ === "professionalServices" ? {
        professionalServices: value.professionalServices
    } : value.__kind__ === "education" ? {
        education: value.education
    } : value.__kind__ === "security" ? {
        security: value.security
    } : value.__kind__ === "consulting" ? {
        consulting: value.consulting
    } : value.__kind__ === "personalServices" ? {
        personalServices: value.personalServices
    } : value.__kind__ === "skilledTrade" ? {
        skilledTrade: value.skilledTrade
    } : value.__kind__ === "legal" ? {
        legal: value.legal
    } : value.__kind__ === "sales" ? {
        sales: value.sales
    } : value.__kind__ === "domesticwork" ? {
        domesticwork: value.domesticwork
    } : value.__kind__ === "petServices" ? {
        petServices: value.petServices
    } : value.__kind__ === "socialServices" ? {
        socialServices: value.socialServices
    } : value.__kind__ === "events" ? {
        events: value.events
    } : value.__kind__ === "maintenance" ? {
        maintenance: value.maintenance
    } : value.__kind__ === "wellness" ? {
        wellness: value.wellness
    } : value.__kind__ === "catering" ? {
        catering: value.catering
    } : value.__kind__ === "manufacturing" ? {
        manufacturing: value.manufacturing
    } : value.__kind__ === "unskilledLabor" ? {
        unskilledLabor: value.unskilledLabor
    } : value.__kind__ === "handyman" ? {
        handyman: value.handyman
    } : value.__kind__ === "hairAndBeauty" ? {
        hairAndBeauty: value.hairAndBeauty
    } : value.__kind__ === "mediar" ? {
        mediar: value.mediar
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OtpRole): {
    client: null;
} | {
    provider: null;
} {
    return value == OtpRole.client ? {
        client: null
    } : value == OtpRole.provider ? {
        provider: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    client: null;
} | {
    provider: null;
} | {
    backOffice: null;
} {
    return value == UserRole.client ? {
        client: null
    } : value == UserRole.provider ? {
        provider: null
    } : value == UserRole.backOffice ? {
        backOffice: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    goodConductCertificate: null;
} | {
    academicQualification: null;
} {
    return value == DocumentType.goodConductCertificate ? {
        goodConductCertificate: null
    } : value == DocumentType.academicQualification ? {
        academicQualification: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
}): {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: string;
} {
    return value.__kind__ === "verified" ? {
        verified: value.verified
    } : value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "unverified" ? {
        unverified: value.unverified
    } : value.__kind__ === "rejected" ? {
        rejected: value.rejected
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Document>): Promise<Array<_Document>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Document_n56(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
