/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProviderProfileView {
    principal: Principal;
    name: string;
    rate: bigint;
    businessType: BusinessType;
    ratings: Array<bigint>;
    description: string;
    phoneNumber: string;
    profilePicture?: ProfilePicture;
    location: Location;
    verificationStatus: VerificationStatus;
}
export interface Location {
    latitude: number;
    longitude: number;
    address: string;
}
export type BusinessType = {
    __kind__: "it";
    it: null;
} | {
    __kind__: "retail";
    retail: null;
} | {
    __kind__: "healthcare";
    healthcare: null;
} | {
    __kind__: "transportation";
    transportation: null;
} | {
    __kind__: "hospitality";
    hospitality: null;
} | {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "realEstate";
    realEstate: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "construction";
    construction: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "marketing";
    marketing: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "consulting";
    consulting: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
} | {
    __kind__: "wellness";
    wellness: null;
} | {
    __kind__: "catering";
    catering: null;
} | {
    __kind__: "manufacturing";
    manufacturing: null;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ProfilePicture {
    id: string;
    blob: ExternalBlob;
}
export type VerificationStatus = {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
};
export interface Job {
    id: string;
    status: {
        __kind__: "requested";
        requested: null;
    } | {
        __kind__: "cancelled";
        cancelled: string;
    } | {
        __kind__: "completed";
        completed: {
            rating: bigint;
        };
    } | {
        __kind__: "inProgress";
        inProgress: null;
    };
    client: Principal;
    provider: Principal;
    description: string;
    payment: bigint;
}
export interface UserProfileView {
    role: UserRole;
    clientProfile?: ClientProfile;
    providerProfile?: ProviderProfileView;
}
export interface ClientProfile {
    principal: Principal;
    phoneNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    client = "client",
    provider = "provider",
    backOffice = "backOffice"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelJob(jobId: string, reason: string): Promise<void>;
    createOrUpdateClientProfile(phoneNumber: string): Promise<void>;
    createOrUpdateProviderProfile(name: string, rate: bigint, businessType: BusinessType, location: Location, phoneNumber: string, description: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClient(client: Principal): Promise<ClientProfile | null>;
    getJob(jobId: string): Promise<Job | null>;
    getProvider(provider: Principal): Promise<ProviderProfileView | null>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    isCallerAdmin(): Promise<boolean>;
    markJobCompleted(jobId: string, rating: bigint): Promise<void>;
    markJobInProgress(jobId: string): Promise<void>;
    requestLink(provider: Principal, payment: bigint, jobDescription: string): Promise<string>;
    saveCallerUserProfile(profile: {
        role: UserRole;
        clientProfile?: {
            principal: Principal;
            phoneNumber: string;
        };
        providerProfile?: {
            principal: Principal;
            name: string;
            rate: bigint;
            businessType: BusinessType;
            ratings: Array<bigint>;
            description: string;
            phoneNumber: string;
            profilePicture?: ProfilePicture;
            location: Location;
            verificationStatus: VerificationStatus;
        };
    }): Promise<void>;
    searchProviders(filterBusinessType: BusinessType | null, _userLocation: Location, _maxDistance: bigint | null): Promise<Array<ProviderProfileView>>;
    setUserRole(role: UserRole): Promise<void>;
    updateVerificationStatus(provider: Principal, status: VerificationStatus): Promise<void>;
}
import type { BusinessType as _BusinessType, ClientProfile as _ClientProfile, ExternalBlob as _ExternalBlob, Job as _Job, Location as _Location, ProfilePicture as _ProfilePicture, ProviderProfileView as _ProviderProfileView, UserProfileView as _UserProfileView, UserRole as _UserRole, UserRole__1 as _UserRole__1, VerificationStatus as _VerificationStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelJob(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelJob(arg0, arg1);
            return result;
        }
    }
    async createOrUpdateClientProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateClientProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateClientProfile(arg0);
            return result;
        }
    }
    async createOrUpdateProviderProfile(arg0: string, arg1: bigint, arg2: BusinessType, arg3: Location, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProviderProfile(arg0, arg1, to_candid_BusinessType_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProviderProfile(arg0, arg1, to_candid_BusinessType_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: Principal): Promise<ClientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProvider(arg0: Principal): Promise<ProviderProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markJobCompleted(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markJobCompleted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markJobCompleted(arg0, arg1);
            return result;
        }
    }
    async markJobInProgress(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markJobInProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markJobInProgress(arg0);
            return result;
        }
    }
    async requestLink(arg0: Principal, arg1: bigint, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestLink(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: {
        role: UserRole;
        clientProfile?: {
            principal: Principal;
            phoneNumber: string;
        };
        providerProfile?: {
            principal: Principal;
            name: string;
            rate: bigint;
            businessType: BusinessType;
            ratings: Array<bigint>;
            description: string;
            phoneNumber: string;
            profilePicture?: ProfilePicture;
            location: Location;
            verificationStatus: VerificationStatus;
        };
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_record_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_record_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProviders(arg0: BusinessType | null, arg1: Location, arg2: bigint | null): Promise<Array<ProviderProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProviders(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n45(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProviders(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n45(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVerificationStatus(arg0: Principal, arg1: VerificationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVerificationStatus(arg0, to_candid_VerificationStatus_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVerificationStatus(arg0, to_candid_VerificationStatus_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BusinessType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessType): BusinessType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Job_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ProfilePicture_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfilePicture): Promise<ProfilePicture> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ProviderProfileView_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderProfileView): Promise<ProviderProfileView> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfileView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): Promise<UserProfileView> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): Promise<UserProfileView | null> {
    return value.length === 0 ? null : await from_candid_UserProfileView_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientProfile]): ClientProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProviderProfileView]): Promise<ProviderProfileView | null> {
    return value.length === 0 ? null : await from_candid_ProviderProfileView_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfilePicture]): Promise<ProfilePicture | null> {
    return value.length === 0 ? null : await from_candid_ProfilePicture_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _UserRole;
    clientProfile: [] | [_ClientProfile];
    providerProfile: [] | [_ProviderProfileView];
}): Promise<{
    role: UserRole;
    clientProfile?: ClientProfile;
    providerProfile?: ProviderProfileView;
}> {
    return {
        role: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.role),
        clientProfile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.clientProfile)),
        providerProfile: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.providerProfile))
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    rate: bigint;
    businessType: _BusinessType;
    ratings: Array<bigint>;
    description: string;
    phoneNumber: string;
    profilePicture: [] | [_ProfilePicture];
    location: _Location;
    verificationStatus: _VerificationStatus;
}): Promise<{
    principal: Principal;
    name: string;
    rate: bigint;
    businessType: BusinessType;
    ratings: Array<bigint>;
    description: string;
    phoneNumber: string;
    profilePicture?: ProfilePicture;
    location: Location;
    verificationStatus: VerificationStatus;
}> {
    return {
        principal: value.principal,
        name: value.name,
        rate: value.rate,
        businessType: from_candid_BusinessType_n21(_uploadFile, _downloadFile, value.businessType),
        ratings: value.ratings,
        description: value.description,
        phoneNumber: value.phoneNumber,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.profilePicture)),
        location: value.location,
        verificationStatus: from_candid_VerificationStatus_n27(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
}): Promise<{
    id: string;
    blob: ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.blob)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        requested: null;
    } | {
        cancelled: string;
    } | {
        completed: {
            rating: bigint;
        };
    } | {
        inProgress: null;
    };
    client: Principal;
    provider: Principal;
    description: string;
    payment: bigint;
}): {
    id: string;
    status: {
        __kind__: "requested";
        requested: null;
    } | {
        __kind__: "cancelled";
        cancelled: string;
    } | {
        __kind__: "completed";
        completed: {
            rating: bigint;
        };
    } | {
        __kind__: "inProgress";
        inProgress: null;
    };
    client: Principal;
    provider: Principal;
    description: string;
    payment: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        client: value.client,
        provider: value.provider,
        description: value.description,
        payment: value.payment
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    provider: null;
} | {
    backOffice: null;
}): UserRole {
    return "client" in value ? UserRole.client : "provider" in value ? UserRole.provider : "backOffice" in value ? UserRole.backOffice : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    it: null;
} | {
    retail: null;
} | {
    healthcare: null;
} | {
    transportation: null;
} | {
    hospitality: null;
} | {
    finance: null;
} | {
    realEstate: null;
} | {
    cleaning: null;
} | {
    construction: null;
} | {
    other: string;
} | {
    marketing: null;
} | {
    education: null;
} | {
    consulting: null;
} | {
    maintenance: null;
} | {
    wellness: null;
} | {
    catering: null;
} | {
    manufacturing: null;
}): {
    __kind__: "it";
    it: null;
} | {
    __kind__: "retail";
    retail: null;
} | {
    __kind__: "healthcare";
    healthcare: null;
} | {
    __kind__: "transportation";
    transportation: null;
} | {
    __kind__: "hospitality";
    hospitality: null;
} | {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "realEstate";
    realEstate: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "construction";
    construction: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "marketing";
    marketing: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "consulting";
    consulting: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
} | {
    __kind__: "wellness";
    wellness: null;
} | {
    __kind__: "catering";
    catering: null;
} | {
    __kind__: "manufacturing";
    manufacturing: null;
} {
    return "it" in value ? {
        __kind__: "it",
        it: value.it
    } : "retail" in value ? {
        __kind__: "retail",
        retail: value.retail
    } : "healthcare" in value ? {
        __kind__: "healthcare",
        healthcare: value.healthcare
    } : "transportation" in value ? {
        __kind__: "transportation",
        transportation: value.transportation
    } : "hospitality" in value ? {
        __kind__: "hospitality",
        hospitality: value.hospitality
    } : "finance" in value ? {
        __kind__: "finance",
        finance: value.finance
    } : "realEstate" in value ? {
        __kind__: "realEstate",
        realEstate: value.realEstate
    } : "cleaning" in value ? {
        __kind__: "cleaning",
        cleaning: value.cleaning
    } : "construction" in value ? {
        __kind__: "construction",
        construction: value.construction
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "marketing" in value ? {
        __kind__: "marketing",
        marketing: value.marketing
    } : "education" in value ? {
        __kind__: "education",
        education: value.education
    } : "consulting" in value ? {
        __kind__: "consulting",
        consulting: value.consulting
    } : "maintenance" in value ? {
        __kind__: "maintenance",
        maintenance: value.maintenance
    } : "wellness" in value ? {
        __kind__: "wellness",
        wellness: value.wellness
    } : "catering" in value ? {
        __kind__: "catering",
        catering: value.catering
    } : "manufacturing" in value ? {
        __kind__: "manufacturing",
        manufacturing: value.manufacturing
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: string;
}): {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
} {
    return "verified" in value ? {
        __kind__: "verified",
        verified: value.verified
    } : "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "unverified" in value ? {
        __kind__: "unverified",
        unverified: value.unverified
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    cancelled: string;
} | {
    completed: {
        rating: bigint;
    };
} | {
    inProgress: null;
}): {
    __kind__: "requested";
    requested: null;
} | {
    __kind__: "cancelled";
    cancelled: string;
} | {
    __kind__: "completed";
    completed: {
        rating: bigint;
    };
} | {
    __kind__: "inProgress";
    inProgress: null;
} {
    return "requested" in value ? {
        __kind__: "requested",
        requested: value.requested
    } : "cancelled" in value ? {
        __kind__: "cancelled",
        cancelled: value.cancelled
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: value.inProgress
    } : value;
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderProfileView>): Promise<Array<ProviderProfileView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ProviderProfileView_n19(_uploadFile, _downloadFile, x)));
}
function to_candid_BusinessType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): _BusinessType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ProfilePicture_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfilePicture): Promise<_ProfilePicture> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType | null): [] | [_BusinessType] {
    return value === null ? candid_none() : candid_some(to_candid_BusinessType_n10(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: UserRole;
    clientProfile?: {
        principal: Principal;
        phoneNumber: string;
    };
    providerProfile?: {
        principal: Principal;
        name: string;
        rate: bigint;
        businessType: BusinessType;
        ratings: Array<bigint>;
        description: string;
        phoneNumber: string;
        profilePicture?: ProfilePicture;
        location: Location;
        verificationStatus: VerificationStatus;
    };
}): Promise<{
    role: _UserRole;
    clientProfile: [] | [{
            principal: Principal;
            phoneNumber: string;
        }];
    providerProfile: [] | [{
            principal: Principal;
            name: string;
            rate: bigint;
            businessType: _BusinessType;
            ratings: Array<bigint>;
            description: string;
            phoneNumber: string;
            profilePicture: [] | [_ProfilePicture];
            location: _Location;
            verificationStatus: _VerificationStatus;
        }];
}> {
    return {
        role: to_candid_UserRole_n36(_uploadFile, _downloadFile, value.role),
        clientProfile: value.clientProfile ? candid_some(value.clientProfile) : candid_none(),
        providerProfile: value.providerProfile ? candid_some(await to_candid_record_n38(_uploadFile, _downloadFile, value.providerProfile)) : candid_none()
    };
}
async function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    rate: bigint;
    businessType: BusinessType;
    ratings: Array<bigint>;
    description: string;
    phoneNumber: string;
    profilePicture?: ProfilePicture;
    location: Location;
    verificationStatus: VerificationStatus;
}): Promise<{
    principal: Principal;
    name: string;
    rate: bigint;
    businessType: _BusinessType;
    ratings: Array<bigint>;
    description: string;
    phoneNumber: string;
    profilePicture: [] | [_ProfilePicture];
    location: _Location;
    verificationStatus: _VerificationStatus;
}> {
    return {
        principal: value.principal,
        name: value.name,
        rate: value.rate,
        businessType: to_candid_BusinessType_n10(_uploadFile, _downloadFile, value.businessType),
        ratings: value.ratings,
        description: value.description,
        phoneNumber: value.phoneNumber,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ProfilePicture_n39(_uploadFile, _downloadFile, value.profilePicture)) : candid_none(),
        location: value.location,
        verificationStatus: to_candid_VerificationStatus_n42(_uploadFile, _downloadFile, value.verificationStatus)
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: ExternalBlob;
}): Promise<{
    id: string;
    blob: _ExternalBlob;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value.blob)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "it";
    it: null;
} | {
    __kind__: "retail";
    retail: null;
} | {
    __kind__: "healthcare";
    healthcare: null;
} | {
    __kind__: "transportation";
    transportation: null;
} | {
    __kind__: "hospitality";
    hospitality: null;
} | {
    __kind__: "finance";
    finance: null;
} | {
    __kind__: "realEstate";
    realEstate: null;
} | {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "construction";
    construction: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "marketing";
    marketing: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "consulting";
    consulting: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
} | {
    __kind__: "wellness";
    wellness: null;
} | {
    __kind__: "catering";
    catering: null;
} | {
    __kind__: "manufacturing";
    manufacturing: null;
}): {
    it: null;
} | {
    retail: null;
} | {
    healthcare: null;
} | {
    transportation: null;
} | {
    hospitality: null;
} | {
    finance: null;
} | {
    realEstate: null;
} | {
    cleaning: null;
} | {
    construction: null;
} | {
    other: string;
} | {
    marketing: null;
} | {
    education: null;
} | {
    consulting: null;
} | {
    maintenance: null;
} | {
    wellness: null;
} | {
    catering: null;
} | {
    manufacturing: null;
} {
    return value.__kind__ === "it" ? {
        it: value.it
    } : value.__kind__ === "retail" ? {
        retail: value.retail
    } : value.__kind__ === "healthcare" ? {
        healthcare: value.healthcare
    } : value.__kind__ === "transportation" ? {
        transportation: value.transportation
    } : value.__kind__ === "hospitality" ? {
        hospitality: value.hospitality
    } : value.__kind__ === "finance" ? {
        finance: value.finance
    } : value.__kind__ === "realEstate" ? {
        realEstate: value.realEstate
    } : value.__kind__ === "cleaning" ? {
        cleaning: value.cleaning
    } : value.__kind__ === "construction" ? {
        construction: value.construction
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "marketing" ? {
        marketing: value.marketing
    } : value.__kind__ === "education" ? {
        education: value.education
    } : value.__kind__ === "consulting" ? {
        consulting: value.consulting
    } : value.__kind__ === "maintenance" ? {
        maintenance: value.maintenance
    } : value.__kind__ === "wellness" ? {
        wellness: value.wellness
    } : value.__kind__ === "catering" ? {
        catering: value.catering
    } : value.__kind__ === "manufacturing" ? {
        manufacturing: value.manufacturing
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    client: null;
} | {
    provider: null;
} | {
    backOffice: null;
} {
    return value == UserRole.client ? {
        client: null
    } : value == UserRole.provider ? {
        provider: null
    } : value == UserRole.backOffice ? {
        backOffice: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
}): {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: string;
} {
    return value.__kind__ === "verified" ? {
        verified: value.verified
    } : value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "unverified" ? {
        unverified: value.unverified
    } : value.__kind__ === "rejected" ? {
        rejected: value.rejected
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
